source 'http://rubygems.org'
gem 'rails', '3.0.7'
#gem 'haml-rails'
gem 'sass'
gem 'devise'
gem 'oa-oauth', :require => 'omniauth/oauth'
gem 'rails3-generators'
gem 'rack-cache', :require => 'rack/cache'
gem 'carrierwave'
gem 'resque'
#gem 'dynamic_form'
gem 'simple_form'
gem 'mini_magick'
gem 'meta_search'
gem 'mlb'
gem 'will_paginate'

group :development, :test do
  gem 'sqlite3-ruby', :require => 'sqlite3'
  gem 'pg'
  gem 'unicorn'
  gem 'ruby-debug19'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'rspec-rails'
  gem 'pickler'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'database_cleaner'
  gem 'fabrication'
end
group :test do
  gem 'testify'
end

