require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlayerGameStatEstimatesController do

  # This should return the minimal set of attributes required to create a valid
  # PlayerGameStatEstimate. As you add validations to PlayerGameStatEstimate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all player_game_stat_estimates as @player_game_stat_estimates" do
      player_game_stat_estimate = PlayerGameStatEstimate.create! valid_attributes
      get :index
      assigns(:player_game_stat_estimates).should eq([player_game_stat_estimate])
    end
  end

  describe "GET show" do
    it "assigns the requested player_game_stat_estimate as @player_game_stat_estimate" do
      player_game_stat_estimate = PlayerGameStatEstimate.create! valid_attributes
      get :show, :id => player_game_stat_estimate.id.to_s
      assigns(:player_game_stat_estimate).should eq(player_game_stat_estimate)
    end
  end

  describe "GET new" do
    it "assigns a new player_game_stat_estimate as @player_game_stat_estimate" do
      get :new
      assigns(:player_game_stat_estimate).should be_a_new(PlayerGameStatEstimate)
    end
  end

  describe "GET edit" do
    it "assigns the requested player_game_stat_estimate as @player_game_stat_estimate" do
      player_game_stat_estimate = PlayerGameStatEstimate.create! valid_attributes
      get :edit, :id => player_game_stat_estimate.id.to_s
      assigns(:player_game_stat_estimate).should eq(player_game_stat_estimate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PlayerGameStatEstimate" do
        expect {
          post :create, :player_game_stat_estimate => valid_attributes
        }.to change(PlayerGameStatEstimate, :count).by(1)
      end

      it "assigns a newly created player_game_stat_estimate as @player_game_stat_estimate" do
        post :create, :player_game_stat_estimate => valid_attributes
        assigns(:player_game_stat_estimate).should be_a(PlayerGameStatEstimate)
        assigns(:player_game_stat_estimate).should be_persisted
      end

      it "redirects to the created player_game_stat_estimate" do
        post :create, :player_game_stat_estimate => valid_attributes
        response.should redirect_to(PlayerGameStatEstimate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved player_game_stat_estimate as @player_game_stat_estimate" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlayerGameStatEstimate.any_instance.stub(:save).and_return(false)
        post :create, :player_game_stat_estimate => {}
        assigns(:player_game_stat_estimate).should be_a_new(PlayerGameStatEstimate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlayerGameStatEstimate.any_instance.stub(:save).and_return(false)
        post :create, :player_game_stat_estimate => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested player_game_stat_estimate" do
        player_game_stat_estimate = PlayerGameStatEstimate.create! valid_attributes
        # Assuming there are no other player_game_stat_estimates in the database, this
        # specifies that the PlayerGameStatEstimate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PlayerGameStatEstimate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => player_game_stat_estimate.id, :player_game_stat_estimate => {'these' => 'params'}
      end

      it "assigns the requested player_game_stat_estimate as @player_game_stat_estimate" do
        player_game_stat_estimate = PlayerGameStatEstimate.create! valid_attributes
        put :update, :id => player_game_stat_estimate.id, :player_game_stat_estimate => valid_attributes
        assigns(:player_game_stat_estimate).should eq(player_game_stat_estimate)
      end

      it "redirects to the player_game_stat_estimate" do
        player_game_stat_estimate = PlayerGameStatEstimate.create! valid_attributes
        put :update, :id => player_game_stat_estimate.id, :player_game_stat_estimate => valid_attributes
        response.should redirect_to(player_game_stat_estimate)
      end
    end

    describe "with invalid params" do
      it "assigns the player_game_stat_estimate as @player_game_stat_estimate" do
        player_game_stat_estimate = PlayerGameStatEstimate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlayerGameStatEstimate.any_instance.stub(:save).and_return(false)
        put :update, :id => player_game_stat_estimate.id.to_s, :player_game_stat_estimate => {}
        assigns(:player_game_stat_estimate).should eq(player_game_stat_estimate)
      end

      it "re-renders the 'edit' template" do
        player_game_stat_estimate = PlayerGameStatEstimate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlayerGameStatEstimate.any_instance.stub(:save).and_return(false)
        put :update, :id => player_game_stat_estimate.id.to_s, :player_game_stat_estimate => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested player_game_stat_estimate" do
      player_game_stat_estimate = PlayerGameStatEstimate.create! valid_attributes
      expect {
        delete :destroy, :id => player_game_stat_estimate.id.to_s
      }.to change(PlayerGameStatEstimate, :count).by(-1)
    end

    it "redirects to the player_game_stat_estimates list" do
      player_game_stat_estimate = PlayerGameStatEstimate.create! valid_attributes
      delete :destroy, :id => player_game_stat_estimate.id.to_s
      response.should redirect_to(player_game_stat_estimates_url)
    end
  end

end
